@startuml
|Система денежных переводов|
start
:POST /api/v1/fraud-checks;
|Anti-fraud System|
:Проверить корректность 
входных данных;
if (Данные корректны?) then (Нет)
:Сформировать ответ: 
невалидные данные;
|Система денежных переводов|
:HTTP 400;
end
|Anti-fraud System|
else (Да)
:POST /api/v1/risk-score;
fork
repeat
:Получить список активных
антифрод-правил из
Fraud Rules DB;
repeat while (Ошибка получения правил 
AND Retry count<3?) is (Да)
->Нет;
if (Правила получены?) then (Нет)
:Отправить на Manual Review;
|Anti-fraud System|
else (Да)
repeat
:Выполнить проверку по
антифрод-правилу;
repeat while (Остались активные правила?) is (Да)
->Нет;
repeat
:Сформировать результат проверки
по антифрод-правилам;
repeat while (Ошибка формирования 
AND Retry count<3?) is (Да)
if (Результат сформирован?) then (Нет)
:Отправить на Manual Review;
else (Да)
endif
endif
fork again
|AI Risk Scoring Service|
:Рассчитать 
уровень 
риска;
|Anti-fraud System|
:Обработать ответ
AI Risk Scoring Service
(при ошибке см. шаг 10 таблицы);
end fork
|Anti-fraud System|
if (Все результаты проверки получены?) then (Да)
:Сформировать итоговое решение
по матрице и сохранить в Fraud Results DB;
if (Approved/Rejected?) then (Да)
:Отправить ответ;
|Система денежных переводов|
:HTTP 200: Approved/Rejected;
stop
else (Нет)
|Anti-fraud System|
endif
else (Нет)
endif
|Антифрод-аналитик|
:Провести
ручную проверку и
сохранить результат в
Fraud Results DB;
if (Одобрено?) then (Да)
:Отправить ответ:
Approved;
else (Нет)
:Отправить ответ:
Rejected;
endif
|Система денежных переводов|
:HTTP 200: Approved/Rejecte;
stop
endif
@enduml